# AWS SAM template for deploying the Lambda function
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: s2r Lambda function for SLURM to Run.ai conversion

Parameters:
  SharedSecret:
    Type: String
    Description: Shared secret for HMAC signature verification
    NoEcho: true
    Default: s2r-shared-secret-change-this-in-production

  BedrockModelId:
    Type: String
    Description: Bedrock model ID to use
    Default: anthropic.claude-sonnet-4-5-20250929-v1:0

  MaxRequestsPerIpPerDay:
    Type: Number
    Description: Maximum requests per IP per day
    Default: 100

Resources:
  # DynamoDB table for rate limiting
  RateLimitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s2r-rate-limits
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ip_date
          AttributeType: S
      KeySchema:
        - AttributeName: ip_date
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl

  # Lambda function
  S2RFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s2r-converter
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          SHARED_SECRET: !Ref SharedSecret
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          MAX_REQUESTS_PER_IP_PER_DAY: !Ref MaxRequestsPerIpPerDay
          RATE_LIMIT_TABLE: !Ref RateLimitTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RateLimitTable
        - Statement:
            - Sid: BedrockInvokeModel
              Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockModelId}'
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

Outputs:
  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt S2RFunctionUrl.FunctionUrl

  RateLimitTableName:
    Description: DynamoDB table for rate limiting
    Value: !Ref RateLimitTable
